{"name": "test_single_user_not_found", "status": "failed", "statusDetails": {"message": "AssertionError: assert None\n +  where None = print({})", "trace": "self = <test_requests.TestGetRequests object at 0x7fe494605730>\n\n    def test_single_user_not_found(self):\n        get_req = requests.get('https://reqres.in/api/users/23')\n        get_req_json = get_req.json()\n        assert get_req.status_code == 404\n>       assert print(get_req_json)\nE       assert None\nE        +  where None = print({})\n\ntest_requests.py:24: AssertionError"}, "start": 1612049328763, "stop": 1612049329346, "uuid": "b4cefe91-87cb-44f4-a67c-c842b6356343", "historyId": "eaf2c4501f3d951cef6f718d8aa6b199", "testCaseId": "adb4cab2bf00c958a764d88657c0f3ff", "fullName": "api_testing.homework3.test_requests.TestGetRequests#test_single_user_not_found", "labels": [{"name": "parentSuite", "value": "api_testing.homework3"}, {"name": "suite", "value": "test_requests"}, {"name": "subSuite", "value": "TestGetRequests"}, {"name": "host", "value": "kali"}, {"name": "thread", "value": "2929-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_testing.homework3.test_requests"}]}